name: Modmail Workflow

on: [push, pull_request]

jobs:
  code-style:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    name: Python ${{ matrix.python-version }} on ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev --system

    - name: Ensure lint tools available
      run: |
        python -m pip install --upgrade \
          ruff==0.8.4 \
          black==23.11.0
    # to refresh: bandit -f json -o .bandit_baseline.json -r . 
    # - name: Bandit syntax check
    #   run: bandit -r . -b .bandit_baseline.json
    - name: Pylint
      run: pylint ./bot.py ./modmail --exit-zero -r y
      continue-on-error: true
    - name: Ruff
      run: ruff check .
    - name: Black
      run: |
        black . --diff --check
    - name: Compile
      run: python -m compileall -q .
